version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
      - 5433:5432
    environment:
      - POSTGRES_USER=joe
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=playground
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
